//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atest.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class DBtestUser
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string BirthODate { get; set; }
        public string Password { get; set; }
        public string UAvatar { get; set; }
        public HttpPostedFileBase Ifile { get; set; }
    }
}
